/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205747;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class UserInputTest {
    @Test void userInputTest(){
        int[] xy = new UserInput().userInput();
        assertEquals(xy.length, 2);
    }  
}
